/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;
import model.User;

/**
 *
 * @author 17814
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    User user;
    public DisplayJPanel(User user) {
        initComponents();
        
        this.user = user;
        displayUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplayUser = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        lblMobileNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblSocSecNum = new javax.swing.JLabel();
        lblMedRecNum = new javax.swing.JLabel();
        lblHealthPlanNum = new javax.swing.JLabel();
        lblBankAccNum = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblVehType = new javax.swing.JLabel();
        lblVehNum = new javax.swing.JLabel();
        lblDeviceId = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblBioId = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtBirthDate = new javax.swing.JTextField();
        txtMobileNum = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        txtSocSecNum = new javax.swing.JTextField();
        txtMedRecNum = new javax.swing.JTextField();
        txtHealthPlanNum = new javax.swing.JTextField();
        txtBankAccNum = new javax.swing.JTextField();
        txtLicNum = new javax.swing.JTextField();
        txtVehType = new javax.swing.JTextField();
        txtVehNum = new javax.swing.JTextField();
        txtDeviceId = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        lblIPAddress = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        lblViewPhoto = new javax.swing.JLabel();

        lblDisplayUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDisplayUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplayUser.setText("User Profile");

        lblFName.setText("Full Name");

        lblAddress.setText("Mailing Address");

        lblBirthDate.setText("Date of Birth");

        lblMobileNum.setText("Mobile Number");

        lblFaxNum.setText("Fax Number");

        lblEmailAddress.setText("Email Address");

        lblSocSecNum.setText("Social Security Number");

        lblMedRecNum.setText("Medical Record Number");

        lblHealthPlanNum.setText("Health Plan Beneficiary Number");

        lblBankAccNum.setText("Bank Account Number");

        lblLicenseNum.setText("License Number");

        lblVehType.setText("Vehicle Type");

        lblVehNum.setText("Vehicle Number");

        lblDeviceId.setText("Device Identifier");

        lblLinkedIn.setText("LinkedIn");

        lblBioId.setText("Biometric Identifier/Photo");

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        txtMobileNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNumActionPerformed(evt);
            }
        });

        txtSocSecNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocSecNumActionPerformed(evt);
            }
        });

        txtMedRecNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedRecNumActionPerformed(evt);
            }
        });

        lblIPAddress.setText("IP Adress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSocSecNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMedRecNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHealthPlanNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBankAccNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVehType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVehNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBioId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHealthPlanNum)
                    .addComponent(txtBankAccNum)
                    .addComponent(txtVehType)
                    .addComponent(txtVehNum)
                    .addComponent(txtDeviceId)
                    .addComponent(txtSocSecNum)
                    .addComponent(txtMedRecNum)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtFName)
                    .addComponent(lblViewPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIPAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLinkedIn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLicenseNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMobileNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBirthDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLicNum)
                    .addComponent(txtLinkedIn)
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobileNum)
                    .addComponent(txtFaxNum)
                    .addComponent(txtEmailId)))
            .addComponent(lblDisplayUser, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, lblAddress, txtBankAccNum, txtBirthDate, txtDeviceId, txtEmailId, txtFName, txtFaxNum, txtHealthPlanNum, txtIPAddress, txtLicNum, txtLinkedIn, txtMedRecNum, txtMobileNum, txtSocSecNum, txtVehNum, txtVehType});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblDisplayUser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFName)
                            .addComponent(lblBirthDate))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblMobileNum)
                        .addGap(12, 12, 12)
                        .addComponent(lblFaxNum)
                        .addGap(12, 12, 12)
                        .addComponent(lblEmailAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMobileNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSocSecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSocSecNum)
                            .addComponent(lblLicenseNum))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedRecNum)
                            .addComponent(lblLinkedIn))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHealthPlanNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHealthPlanNum)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblIPAddress)
                                .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblBankAccNum))
                    .addComponent(txtBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblVehType))
                    .addComponent(txtVehType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblVehNum))
                    .addComponent(txtVehNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDeviceId))
                    .addComponent(txtDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBioId)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblViewPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBankAccNum, txtBirthDate, txtDeviceId, txtFName, txtHealthPlanNum, txtMedRecNum, txtMobileNum, txtSocSecNum, txtVehNum, txtVehType});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmailId, txtFaxNum, txtIPAddress, txtLicNum, txtLinkedIn});

    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtMobileNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNumActionPerformed

    private void txtSocSecNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocSecNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocSecNumActionPerformed

    private void txtMedRecNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedRecNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedRecNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBankAccNum;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblDeviceId;
    private javax.swing.JLabel lblDisplayUser;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblHealthPlanNum;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblMobileNum;
    private javax.swing.JLabel lblSocSecNum;
    private javax.swing.JLabel lblVehNum;
    private javax.swing.JLabel lblVehType;
    private javax.swing.JLabel lblViewPhoto;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBankAccNum;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtDeviceId;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtHealthPlanNum;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLicNum;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedRecNum;
    private javax.swing.JTextField txtMobileNum;
    private javax.swing.JTextField txtSocSecNum;
    private javax.swing.JTextField txtVehNum;
    private javax.swing.JTextField txtVehType;
    // End of variables declaration//GEN-END:variables

    private void displayUser() {
      
        txtFName.setText(user.getfName());
        txtAddress.setText(user.getMailAddress());
        txtBirthDate.setText(user.getbDate());
        txtMobileNum.setText(user.getMobNum());
        txtFaxNum.setText(user.getFaxNum());
        txtEmailId.setText(user.getEmailId());
        txtSocSecNum.setText(user.getSocSecNum());
        txtMedRecNum.setText(user.getMedRecNum());
        txtHealthPlanNum.setText(user.getHealthPlanBenNum());
        txtBankAccNum.setText(user.getBanAccNum());
        txtVehType.setText(user.getVehType());
        txtVehNum.setText(user.getVehNumber());
        txtDeviceId.setText(user.getDevIdNum());
        txtLinkedIn.setText(user.getLinkedinId());
        txtIPAddress.setText(user.getIpAddress());
        lblViewPhoto.setIcon(new ImageIcon(user.getBioId()));
        
    }
        
       
}
